hyperparams:
  logging_level: INFO
  checkpoint_dir: checkpoints
  random_seed: 42
  num_classes: 10
  early_stopping_patience: 5

trainparams:
  batch_size: 100
  learning_rate: 1e-3
  num_epochs: 50
  weight_decay: 5e-3
  criterion: CrossEntropyLoss
  optimizer: AdamW
  dtype: float32

testparams:
  dtype: float32
